version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: mahaseel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-mahaseel}
      POSTGRES_PASSWORD: ${PGPASSWORD:-mahaseel}
      POSTGRES_DB: ${PGDATABASE:-mahaseel}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-mahaseel} -d ${PGDATABASE:-mahaseel}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
