"""create otps table (fix path)

Revision ID: 767d4485d251
Revises: 1a6c43a1015e
Create Date: 2025-08-26 16:41:42.990137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767d4485d251'
down_revision: Union[str, None] = '1a6c43a1015e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_index(op.f('ix_otps_expires_at'), 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otps_phone'), 'otps', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otps_phone'), table_name='otps')
    op.drop_index(op.f('ix_otps_expires_at'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
