"""add ratings table

Revision ID: ae116f6da243
Revises: a06ca17fd413
Create Date: 2025-08-24 14:27:33.965234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae116f6da243'
down_revision: Union[str, None] = 'a06ca17fd413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crops_state_type_created_at'), table_name='crops')
    op.create_index(op.f('ix_crops_created_at'), 'crops', ['created_at'], unique=False)
    op.create_index(op.f('ix_crops_price'), 'crops', ['price'], unique=False)
    op.create_index(op.f('ix_crops_state'), 'crops', ['state'], unique=False)
    op.create_index(op.f('ix_crops_type'), 'crops', ['type'], unique=False)
    op.drop_column('crops', 'seller_name')
    op.drop_column('crops', 'seller_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('seller_phone', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('crops', sa.Column('seller_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_crops_type'), table_name='crops')
    op.drop_index(op.f('ix_crops_state'), table_name='crops')
    op.drop_index(op.f('ix_crops_price'), table_name='crops')
    op.drop_index(op.f('ix_crops_created_at'), table_name='crops')
    op.create_index(op.f('ix_crops_state_type_created_at'), 'crops', ['state', 'type', 'created_at'], unique=False)
    # ### end Alembic commands ###
