"""add media table + one-main-image index

Revision ID: dc3248361508
Revises: 82f8a4f9fb49
Create Date: 2025-08-21 20:27:40.709424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3248361508'
down_revision: Union[str, None] = '82f8a4f9fb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.create_index(op.f('ix_media_is_main'), 'media', ['is_main'], unique=False)
    op.create_index('uq_media_one_per_crop', 'media', ['crop_id'], unique=True, postgres_where=sa.text('is_main = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_media_one_per_crop', table_name='media', postgres_where=sa.text('is_main = true'))
    op.drop_index(op.f('ix_media_is_main'), table_name='media')
    op.alter_column('media', 'path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
