name: mobile-ci
on:
  push:
    branches: [ main, develop ]
    paths: [ "mobile/**", ".github/workflows/mobile-ci.yml" ]
  pull_request:
    paths: [ "mobile/**", ".github/workflows/mobile-ci.yml" ]

jobs:
  analyze-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        working-directory: mobile
        run: flutter pub get

      - name: Analyze
        working-directory: mobile
        run: flutter analyze

      - name: Build debug APK
        working-directory: mobile
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mahaseel-debug-apk
          path: mobile/build/app/outputs/flutter-apk/app-debug.apk
